//
// Created by nray on 4/14/23.
//

#ifndef GIUSEP_PI_DEFINITIONS_H
#define GIUSEP_PI_DEFINITIONS_H

#define SPI_SCK 2
#define SPI_CS  1
#define SPI_SO  0
#define HEALTH_LED 28
#define BOILER_SWITCH_INPUT 4
#define BOILER_RELAY_OUTPUT 16
#define BOILER_SECONDARY_RELAY_OUTPUT 17


#endif //GIUSEP_PI_DEFINITIONS_H
